name: Deploy Ansible
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pipx
              run: |
                sudo apt install pipx
                pipx ensurepath
                
            - name: Install Ansible
              run: pipx install --include-deps ansible

            - name: Install Docker
              run: apt install -y docker-ce

            - name: Install ContainerLab
              run: |
                echo "deb [trusted=yes] https://apt.fury.io/netdevops/ /" | \
                tee -a /etc/apt/sources.list.d/netdevops.list
                apt update && apt install containerlab

            - name: Start ContainerLab with topology
              run: containerlab deploy --topo topology.yml